version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb-blockchain
    restart: always
    ports:
      - 27027:27027
    environment:
      - MONGO_INITDB_DATABASE=blockchain
      - MONGO_PORT=27027
    volumes:
      - ./data/db:/data/db
    networks:
      -  blockchain-network
    command: --auth

networks:
  blockchain-network:
    driver: bridge
