version: "3.2"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-blockchain
    hostname: postgres-blockchain
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      PGTZ: Sao_Paulo/Brazil
      TZ: Sao_Paulo/Brazil
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres-volume:
    name: postgres-volume
    driver: local

networks:
  default:
    name: blockchain-network
    driver: bridge